name: Test Repository Rulesets
on:
  workflow_dispatch:  # Permite ejecutarlo manualmente
jobs:
  create-rulesets:
    runs-on: ubuntu-latest
    steps:
      - name: Create default branch ruleset
        run: |
          curl --request POST \
            --url "https://api.github.com/repos/${{ github.repository }}/rulesets" \
            --header "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            --header "Content-Type: application/json" \
            --data '{
              "name": "Block version-like branches",
              "target": "branch",
              "enforcement": "active",
              "conditions": {
                "ref_name": {
                  "exclude": ["refs/heads/[0-9]*.[0-9]*"],
                  "include": ["~ALL"]
                }
              },
              "rules": [{"type": "creation"}]
            }'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
